In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("sachin_emotion_dataset_large.csv")

In [3]:
df.sample(10)

                                                  Text        Label
687  Raat ke baad hi subah aati hai. Khud se wada hai.    Inspiring
750                    Teri bhakti mein hi shanti hai.   Devotional
900  Teri kripa se hi sab sambhav hai. Khud se wada...   Devotional
734    Manzil unhi ko milti hai jo rukte nahi. Dil se.    Inspiring
35    Teri baaton mein ghar jaisa sukoon hai. Hamesha.     Romantic
252       Tumhare bina ghar khaali lagta hai. Aaj bhi.  Melancholic
86   Teri muskaan se hi meri subah roshan hoti hai....     Romantic
326   Bheed mein bhi ek ajeeb sa akelapan hai. Dil se.  Melancholic
625           Raat ke baad hi subah aati hai. Aaj bhi.    Inspiring
211    Teri baaton mein ghar jaisa sukoon hai. Dil se.     Romantic

In [4]:
df.rename(columns = {"Text" : "text", "Label" : "label"}, inplace = True)

In [5]:
df.head()

                                                text     label
0             Tum meri saanson ki aadat ban gaye ho.  Romantic
1  Tere bina har khushi adhoori si lagti hai. Khu...  Romantic
2  Teri khamoshi bhi mujhe sab keh jaati hai. Dil...  Romantic
3  Tum saath ho to har darr chhota lagta hai. Har...  Romantic
4         Tere bina har khushi adhoori si lagti hai.  Romantic