In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("sachin_emotion_dataset_large.csv")

In [3]:
df.sample(10)

                                                  Text       Label
579  Sapne unhi ke sach hote hain jo mehnat karte h...   Inspiring
79   Tum saath ho to har darr chhota lagta hai. Dil...    Romantic
82   Tum saath ho to har darr chhota lagta hai. Har...    Romantic
50   Teri baaton mein ghar jaisa sukoon hai. Khud s...    Romantic
733             Toofan mazbooti parakhte hain. Dil se.   Inspiring
225         Tere bina har khushi adhoori si lagti hai.    Romantic
653            Manzil unhi ko milti hai jo rukte nahi.   Inspiring
123  Teri muskaan se hi meri subah roshan hoti hai....    Romantic
913  Prabhu, bas itni shakti de ki kabhi toot na ja...  Devotional
706           Raat ke baad hi subah aati hai. Har pal.   Inspiring

In [4]:
df.rename(columns = {"Text" : "text", "Label" : "label"}, inplace = True)

In [5]:
df.head()

                                                text     label
0             Tum meri saanson ki aadat ban gaye ho.  Romantic
1  Tere bina har khushi adhoori si lagti hai. Khu...  Romantic
2  Teri khamoshi bhi mujhe sab keh jaati hai. Dil...  Romantic
3  Tum saath ho to har darr chhota lagta hai. Har...  Romantic
4         Tere bina har khushi adhoori si lagti hai.  Romantic

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["label_encoded"] = le.fit_transform(df["label"])

In [9]:
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Label Mapping (Kaunsa number kiska hai?):", label_mapping)

Label Mapping (Kaunsa number kiska hai?): {'Devotional': np.int64(0), 'Inspiring': np.int64(1), 'Melancholic': np.int64(2), 'Romantic': np.int64(3)}

In [11]:
from sklearn.model_selection import train_test_split
train_text, test_text, train_labels, test_labels = train_test_split(
    df["text"].tolist(), df["label_encoded"].tolist(), test_size=0.2, random_state=42
)

In [13]:
print(f"\nTotal lines for Training: {len(train_text)}")
print(f"Total lines for Testing: {len(test_text)}")
print("\nSample Train Text:", train_text[0])
print("Uska Label:", train_labels[0])

Total lines for Training: 800
Total lines for Testing: 200

Sample Train Text: Teri baaton mein ghar jaisa sukoon hai. Hamesha.
Uska Label: 3

In [ ]:
import tensorflow as tf
from transformers import AutoTokenizer

In [ ]:
model_name = "distilbert-base-multingual"